# Generated by Django 2.2.1 on 2019-05-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryEntryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=40, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryEntryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, verbose_name='Category')),
                ('category_parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.GalleryEntryCategory', verbose_name='Parent Category')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('entry_file_url', models.FileField(default='', upload_to='', verbose_name='File')),
                ('entry_desc', models.TextField(default='', verbose_name='Description')),
                ('entry_desc_full', models.TextField(default='', verbose_name='Full Description')),
                ('entry_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.GalleryEntryCategory', verbose_name='Category')),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.GalleryEntryType', verbose_name='Type')),
            ],
        ),
    ]
