# Generated by Django 2.1.7 on 2019-03-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmodel',
            name='conf_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
